###############################################################################
#
# Copyright (C) 2020 Tom Kralidis
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

version: "3"

volumes:
  esdata01:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch-01
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch-01
      - discovery.seed_hosts=elasticsearch-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  geomet-data-registry:
    container_name: geomet-data-registry-container
    depends_on:
      - elasticsearch
      - redis
    environment:
      - GDR_LOGGING_LOGLEVEL=DEBUG
      - GDR_LOGGING_LOGFILE=/tmp/geomet-data-registry-dev.log
      - GDR_CONFIG=/opt/geomet-data-registry/geomet-data-registry.yml
      - GDR_BASEDIR=/home/geoadm/geomet-data-registry
      - GDR_DATADIR=/data/geomet/data/feeds
      - GDR_URL=http://localhost/geomet-data-registry
      - GDR_TILEINDEX_TYPE=Elasticsearch
      - GDR_TILEINDEX_BASEURL=http://elasticsearch:9200
      - GDR_TILEINDEX_NAME=geomet-data-registry-tileindex
      - GDR_STORE_TYPE=Redis
      - GDR_STORE_URL=redis://redis:6379
      - XDG_CACHE_HOME=/tmp/geomet-data-registry-logs
    build:
      context: ..

networks:
  default:
    external:
      name: geomet-data-registry-network
