###############################################################################
#
# Copyright (C) 2021 Tom Kralidis
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

version: "3"

services:
  geomet-data-registry:
    container_name: geomet-data-registry
    environment:
      - GDR_LOGGING_LOGLEVEL=DEBUG
      - GDR_LOGGING_LOGFILE=/tmp/geomet-data-registry-nightly.log
      - GDR_CONFIG=/opt/geomet-data-registry/geomet-data-registry.yml
      - GDR_BASEDIR=/home/geoadm/geomet-data-registry
      - GDR_DATADIR=/data/geomet/feeds
      - GDR_TILEINDEX_TYPE=Elasticsearch
      - GDR_TILEINDEX_BASEURL=http://localhost:9200
      - GDR_TILEINDEX_NAME=geomet-data-registry-nightly
      - GDR_STORE_TYPE=Redis
      - GDR_STORE_URL=redis://localhost:6379?db=15
      - GDR_METPX_DISCARD=on
      - GDR_METPX_EVENT_PY=/home/geoadm/geomet-data-registry/geomet_data_registry/event.py
      - GDR_METPX_NOTIFY=True
      - GDR_GEOMET_ONLY_USER=username
      - GDR_GEOMET_ONLY_PASS=password
      - GDR_GEOMET_ONLY_HOST=feeds.example.org
      - GDR_NOTIFICATIONS=False
      - GDR_NOTIFICATIONS_TYPE=Celery
      - GDR_NOTIFICATIONS_URL=redis://localhost:6379?db=15
      - XDG_CACHE_HOME=/tmp/geomet-data-registry-nightly-sarra-logs

    volumes:
      - /tmp:/tmp
    network_mode: host

    build:
      context: ..
