gdwps:
    model: GDWPS
    filename_pattern: '{YYYYMMDD}T{model_run}Z_MSC_GDWPS_{wx_variable}_LatLon0.25_PT{forecast_hour}H.grib2'
    dimensions:
        x: 1440
        y: 721
    model_run_retention_hours: 48
    model_run_interval_hours: 12
    variable:
        HTSGW_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_HTSGW_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_HTSGW_PT3H:
                    forecast_hours: 000/120/PT3H
        ICEC_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_ICEC_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_ICEC_PT3H:
                    forecast_hours: 000/120/PT3H
        MWDFSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_MWDFSWEL_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_MWDFSWEL_PT3H:
                    forecast_hours: 000/120/PT3H
        MWDSSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_MWDSSWEL_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_MWDSSWEL_PT3H:
                    forecast_hours: 000/120/PT3H
        MZWPER_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_MZWPER_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_MZWPER_PT3H:
                    forecast_hours: 000/120/PT3H
        PPERWW_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_PPERWW_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_PPERWW_PT3H:
                    forecast_hours: 000/120/PT3H
        PWAVEDIR_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_PWAVEDIR_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_PWAVEDIR_PT3H:
                    forecast_hours: 000/120/PT3H
        PWPER_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_PWPER_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_PWPER_PT3H:
                    forecast_hours: 000/120/PT3H
        PWPFSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_PWPFSWEL_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_PWPFSWEL_PT3H:
                    forecast_hours: 000/120/PT3H
        PWPSSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_PWPSSWEL_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_PWPSSWEL_PT3H:
                    forecast_hours: 000/120/PT3H
        SWHFSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_SWHFSWEL_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_SWHFSWEL_PT3H:
                    forecast_hours: 000/120/PT3H
        SWHSSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_SWHSSWEL_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_SWHSSWEL_PT3H:
                    forecast_hours: 000/120/PT3H
        UGRD_AGL-10m:
            members: null
            elevation: 10m
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_UGRD_10m_PT1H:
                    published: False
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_UGRD_10m_PT3H:
                    published: False
                    forecast_hours: 000/120/PT3H
                GDWPS_25km_Winds_10m_PT1H:
                    dependencies:
                        - GDWPS_25km_VGRD_10m_PT1H
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_Winds_10m_PT3H:
                    dependencies:
                        - GDWPS_25km_VGRD_10m_PT3H
                    forecast_hours: 000/120/PT3H
            bands_order:
                - UGRD_AGL-10m
                - VGRD_AGL-10m
        VGRD_AGL-10m:
            members: null
            elevation: 10m
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_VGRD_10m_PT1H:
                    published: False
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_VGRD_10m_PT3H:
                    published: False
                    forecast_hours: 000/120/PT3H
                GDWPS_25km_Winds_10m_PT1H:
                    dependencies:
                        - GDWPS_25km_UGRD_10m_PT1H
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_Winds_10m_PT3H:
                    dependencies:
                        - GDWPS_25km_UGRD_10m_PT3H
                    forecast_hours: 000/120/PT3H
            bands_order:
                - UGRD_AGL-10m
                - VGRD_AGL-10m
        WVDIR_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_WVDIR_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_WVDIR_PT3H:
                    forecast_hours: 000/120/PT3H
        WVHGT_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 73
                12Z:
                    files_expected: 73
            geomet_layers:
                GDWPS_25km_WVHGT_PT1H:
                    forecast_hours: 000/048/PT1H
                GDWPS_25km_WVHGT_PT3H:
                    forecast_hours: 000/120/PT3H
