rdwps:
    model: RDWPS
    filename_pattern: '{YYYYMMDD}T{model_run}Z_MSC_RDWPS-{region}_{wx_variable:NonWhitespaceChars}_{grid}_PT{forecast_hour}H.grib2'
    model_run_retention_hours: 48
    model_run_interval_hours: 6
    dimensions:
        Erie:
            x: 398
            y: 210
        Huron-Michigan:
            x: 698
            y: 573
        Ontario:
            x: 348
            y: 158
        Superior:
            x: 658
            y: 318
        Atlantic-North-West:
            x: 762
            y: 643
    variable:
        HTSGW_sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_HTSGW:
                    forecast_hours: 000/048/PT1H
        ICEC_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_ICEC:
                    forecast_hours: 000/048/PT1H
        MWDFSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_MWDFSWEL:
                    forecast_hours: 000/048/PT1H
        MWDSSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_MWDSSWEL:
                    forecast_hours: 000/048/PT1H
        MZWPER_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_MZWPER:
                    forecast_hours: 000/048/PT1H
        PPERWW_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_PPERWW:
                    forecast_hours: 000/048/PT1H
        PWAVEDIR_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_PWAVEDIR:
                    forecast_hours: 000/048/PT1H
        PWPER_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_PWPER:
                    forecast_hours: 000/048/PT1H
        PWPFSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_PWPFSWEL:
                    forecast_hours: 000/048/PT1H
        PWPSSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_PWPSSWEL:
                    forecast_hours: 000/048/PT1H
        SWHFSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_SWHFSWEL:
                    forecast_hours: 000/048/PT1H
        SWHSSWEL_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_SWHSSWEL:
                    forecast_hours: 000/048/PT1H
        UGRD_AGL-10m:
            members: null
            elevation: 10m
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_UGRD_10m:
                    published: False
                    forecast_hours: 000/048/PT1H
                RDWPS-{}_{}_Winds_10m:
                    dependencies:
                        - RDWPS-{}_{}_VGRD_10m
                    forecast_hours: 000/048/PT1H
            bands_order:
                - UGRD_AGL-10m
                - VGRD_AGL-10m
        VGRD_AGL-10m:
            members: null
            elevation: 10m
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_VGRD_10m:
                    published: False
                    forecast_hours: 000/048/PT1H
                RDWPS-{}_{}_Winds_10m:
                    dependencies:
                        - RDWPS-{}_{}_UGRD_10m
                    forecast_hours: 000/048/PT1H
            bands_order:
                - UGRD_AGL-10m
                - VGRD_AGL-10m
        WVDIR_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_WVDIR:
                    forecast_hours: 000/048/PT1H
        WVHGT_Sfc:
            members: null
            elevation: surface
            model_run:
                00Z:
                    files_expected: 49
                06Z:
                    files_expected: 49
                12Z:
                    files_expected: 49
                18Z:
                    files_expected: 49
            geomet_layers:
                RDWPS-{}_{}_WVHGT:
                    forecast_hours: 000/048/PT1H
